import { 
  User, 
  Class, 
  SubscriptionPackage, 
  Achievement,
  Workout,
  HealthMetrics 
} from './types';

export const mockUser: User = {
  id: '1',
  name: 'דני כהן',
  email: 'danny@example.com',
  role: 'user',
  profileImage: 'https://i.pravatar.cc/150?img=12',
  subscription: {
    type: 'premium',
    status: 'active',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    classesPerMonth: 12,
    classesUsed: 5,
  },
  achievements: [],
  totalWorkouts: 24,
  weeklyGoal: 4,
  currentStreak: 7,
};

export const mockCoach: User = {
  id: '2',
  name: 'שרה לוי',
  email: 'sarah@example.com',
  role: 'coach',
  profileImage: 'https://i.pravatar.cc/150?img=5',
  achievements: [],
  totalWorkouts: 0,
  weeklyGoal: 0,
  currentStreak: 0,
};

export const mockClasses: Class[] = [
  {
    id: '1',
    title: 'HIIT בוקר אנרגטי',
    description: 'אימון אינטנסיבי לשריפת קלוריות והגברת כושר',
    instructor: 'שרה לוי',
    instructorImage: 'https://i.pravatar.cc/150?img=5',
    date: '2025-11-04',
    time: '07:00',
    duration: 45,
    capacity: 20,
    enrolled: 12,
    type: 'hiit',
    difficulty: 'intermediate',
    location: 'אולם 1',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '2',
    title: 'יוגה בשקיעה',
    description: 'יוגה מרגיעה לסיום היום',
    instructor: 'מיכל אברהם',
    instructorImage: 'https://i.pravatar.cc/150?img=9',
    date: '2025-11-04',
    time: '18:30',
    duration: 60,
    capacity: 15,
    enrolled: 8,
    type: 'yoga',
    difficulty: 'beginner',
    location: 'אולם 2',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '3',
    title: 'אגרוף מתקדם',
    description: 'טכניקות אגרוף מתקדמות ואימון קרדיו',
    instructor: 'יוסי כהן',
    instructorImage: 'https://i.pravatar.cc/150?img=33',
    date: '2025-11-05',
    time: '19:00',
    duration: 50,
    capacity: 12,
    enrolled: 12,
    type: 'boxing',
    difficulty: 'advanced',
    location: 'אולם 3',
    requiredSubscription: ['premium', 'vip'],
  },
  {
    id: '4',
    title: 'פילאטיס בבוקר',
    description: 'חיזוק שרירי הליבה ושיפור הגמישות',
    instructor: 'רונית דוד',
    instructorImage: 'https://i.pravatar.cc/150?img=10',
    date: '2025-11-05',
    time: '08:00',
    duration: 55,
    capacity: 18,
    enrolled: 14,
    type: 'pilates',
    difficulty: 'intermediate',
    location: 'אולם 2',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '5',
    title: 'כוח מלא',
    description: 'אימון כוח אינטנסיבי עם משקולות',
    instructor: 'אורי מזרחי',
    instructorImage: 'https://i.pravatar.cc/150?img=68',
    date: '2025-11-06',
    time: '17:00',
    duration: 60,
    capacity: 15,
    enrolled: 9,
    type: 'strength',
    difficulty: 'advanced',
    location: 'חדר כושר',
    requiredSubscription: ['premium', 'vip'],
  },
];

export const subscriptionPackages: SubscriptionPackage[] = [
  {
    id: '1',
    type: 'basic',
    name: 'בסיסי',
    price: 199,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 8,
    features: [
      '8 שיעורים בחודש',
      'גישה לאפליקציה',
      'מעקב אימונים',
      'הישגים ואתגרים',
    ],
  },
  {
    id: '2',
    type: 'premium',
    name: 'פרימיום',
    price: 349,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 12,
    popular: true,
    features: [
      '12 שיעורים בחודש',
      'גישה לכל השיעורים',
      'תוכנית אימונים אישית',
      'מעקב תזונה',
      'ייעוץ אישי חודשי',
      'אינטגרציה עם אפליקציות בריאות',
    ],
  },
  {
    id: '3',
    type: 'vip',
    name: 'VIP',
    price: 599,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 20,
    features: [
      'שיעורים ללא הגבלה',
      'כל מה שכלול בפרימיום',
      'אימונים אישיים (2 בחודש)',
      'עדיפות בהרשמה לשיעורים',
      'גישה לאירועים מיוחדים',
      'ייעוץ תזונאי אישי',
      'מעקב מתקדם עם ניתוח ביצועים',
    ],
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    title: 'אימון ראשון',
    description: 'השלם את האימון הראשון שלך',
    icon: 'trophy',
    progress: 1,
    target: 1,
    completed: true,
    dateEarned: '2025-10-01',
  },
  {
    id: '2',
    title: 'רצף שבועי',
    description: 'אמן 7 ימים ברצף',
    icon: 'flame',
    progress: 7,
    target: 7,
    completed: true,
    dateEarned: '2025-10-15',
  },
  {
    id: '3',
    title: '10 אימונים',
    description: 'השלם 10 אימונים',
    icon: 'award',
    progress: 10,
    target: 10,
    completed: true,
    dateEarned: '2025-10-20',
  },
  {
    id: '4',
    title: 'רצף חודשי',
    description: 'אמן 30 ימים ברצף',
    icon: 'star',
    progress: 15,
    target: 30,
    completed: false,
  },
  {
    id: '5',
    title: '50 אימוני��',
    description: 'השלם 50 אימונים',
    icon: 'medal',
    progress: 24,
    target: 50,
    completed: false,
  },
];

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    userId: '1',
    title: 'אימון בוקר',
    date: '2025-11-03',
    duration: 45,
    calories: 350,
    type: 'strength',
    heartRateAvg: 135,
    heartRateMax: 165,
    exercises: [
      { id: '1', name: 'סקוואט', sets: 4, reps: 12, weight: 60 },
      { id: '2', name: 'בנץ\' פרס', sets: 4, reps: 10, weight: 50 },
      { id: '3', name: 'משיכות', sets: 3, reps: 8, weight: 40 },
    ],
  },
  {
    id: '2',
    userId: '1',
    title: 'ריצה בפארק',
    date: '2025-11-02',
    duration: 30,
    calories: 280,
    type: 'cardio',
    heartRateAvg: 142,
    heartRateMax: 175,
    distance: 5.2,
    exercises: [],
  },
];

export const mockHealthMetrics: HealthMetrics[] = [
  {
    date: '2025-11-03',
    steps: 8542,
    activeMinutes: 45,
    calories: 2340,
    distance: 6.2,
    heartRateResting: 62,
    sleep: 7.5,
  },
  {
    date: '2025-11-02',
    steps: 10234,
    activeMinutes: 60,
    calories: 2580,
    distance: 7.8,
    heartRateResting: 60,
    sleep: 8.0,
  },
];

export const mockUsers: User[] = [
  mockUser,
  {
    id: '3',
    name: 'מיכל רוזנברג',
    email: 'michal@example.com',
    role: 'user',
    profileImage: 'https://i.pravatar.cc/150?img=20',
    subscription: {
      type: 'basic',
      status: 'active',
      startDate: '2025-10-01',
      endDate: '2025-11-01',
      classesPerMonth: 8,
      classesUsed: 6,
    },
    achievements: mockAchievements.slice(0, 2),
    totalWorkouts: 15,
    weeklyGoal: 3,
    currentStreak: 3,
  },
  {
    id: '4',
    name: 'יוסי אברהם',
    email: 'yossi@example.com',
    role: 'user',
    profileImage: 'https://i.pravatar.cc/150?img=52',
    subscription: {
      type: 'vip',
      status: 'active',
      startDate: '2025-09-01',
      endDate: '2025-12-01',
      classesPerMonth: 20,
      classesUsed: 12,
    },
    achievements: mockAchievements.slice(0, 3),
    totalWorkouts: 42,
    weeklyGoal: 5,
    currentStreak: 14,
  },
];
